Update config installation to better support jessie and wheezy.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -57,15 +57,45 @@ case "$1" in
             cp /usr/share/amppki/production.ini-dist /usr/share/amppki/production.ini
         fi
 
-        # enable the SSL module
-        /usr/sbin/a2enmod ssl
-
-        if apache2ctl configtest 2>/dev/null; then
-            #invoke-rc.d apache2 force-reload || true
-            # use "restart" as a workaround for bug #558608
-            invoke-rc.d apache2 restart || true
+        # TODO use dh_apache2
+        RESTART=false
+        if [ -d /etc/apache2/conf-available/ ]; then
+            # try to install the config for apache2 in jessie or similar
+            if [ ! -e /etc/apache2/conf-available/amppki.conf ]; then
+                ln -s /usr/share/amppki/amppki.conf /etc/apache2/conf-available/
+                /usr/sbin/a2enconf -q amppki
+                RESTART=true
+            fi
+        elif [ -d /etc/apache2/conf.d/ ]; then
+            # try to install the config for apache2 in wheezy or similar
+            if [ ! -e /etc/apache2/conf.d/amppki.conf ]; then
+                ln -s /usr/share/amppki/amppki.conf /etc/apache2/conf.d/
+                RESTART=true
+            fi
         else
-            echo "Your apache2 configuration is broken, please fix it and restart apache2 manually."
+            echo "ERROR: Couldn't determine apache2 configuration directory"
+            exit 1
+        fi
+
+        # check if the ssl module is enabled
+        if ! apache2ctl -M | awk '{print $1}' | grep -qx ssl_module; then
+            # enable the SSL module
+            if /usr/sbin/a2enmod -q ssl; then
+                RESTART=true
+            else
+                echo "Failed to enable apache2 ssl module"
+            fi
+        fi
+
+        # restart if we enabled the config or the ssl module
+        if $RESTART; then
+            if apache2ctl configtest 2>/dev/null; then
+                #invoke-rc.d apache2 force-reload || true
+                # use "restart" as a workaround for bug #558608
+                invoke-rc.d apache2 restart || true
+            else
+                echo "Your apache2 configuration is broken, please fix it and restart apache2 manually."
+            fi
         fi
     ;;
 
